services:
  - type: web
    name: manforia-reading-tracker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123

databases:
  - name: manforia-reading-db
    databaseName: manforia_reading_tracker
    user: manforia_user
    plan: free
